### ISSUE TITLE
Fody runs out of memory with Mono 5

### ISSUE THREAD

**Issue by meherkasam** [Fody/Fody#332]
I am using Fody through Realm for Xamarin. After upgrading to the latest version, I am seeing this error:

: error : Fody: An unhandled exception occurred:
Exception:
Out of memory
StackTrace:
  at (wrapper alloc) System.Object:AllocVector (intptr,intptr)
  at Microsoft.Cci.Pdb.MsfDirectory..ctor (Microsoft.Cci.Pdb.PdbReader reader, Microsoft.Cci.Pdb.PdbFileHeader head, Microsoft.Cci.Pdb.BitAccess bits) [0x000a5] in <d39e61ae2787473a851567b860d13696>:0 
  at Microsoft.Cci.Pdb.PdbFile.LoadFunctions (System.IO.Stream read, System.Collections.Generic.Dictionary`2[System.UInt32,Microsoft.Cci.Pdb.PdbTokenLine]& tokenToSourceMapping, System.String& sourceServerData, System.Int32& age, System.Guid& guid) [0x00027] in <d39e61ae2787473a851567b860d13696>:0 
  at Mono.Cecil.Pdb.PdbReader.PopulateFunctions () [0x00008] in <d39e61ae2787473a851567b860d13696>:0 
  at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader (Mono.Cecil.Cil.ImageDebugDirectory directory, System.Byte[] header) [0x00048] in <d39e61ae2787473a851567b860d13696>:0 
  at Mono.Cecil.ModuleDefinition.ProcessDebugHeader () [0x00012] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleDefinition.ReadSymbols (Mono.Cecil.Cil.ISymbolReader reader) [0x00015] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleReader.ReadSymbols (Mono.Cecil.ModuleDefinition module, Mono.Cecil.ReaderParameters parameters) [0x00047] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleReader.CreateModuleFrom (Mono.Cecil.PE.Image image, Mono.Cecil.ReaderParameters parameters) [0x00076] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream, Mono.Cecil.ReaderParameters parameters) [0x00028] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0000a] in <b5a52cab1f0046ce9f68342127787868>:0 
  at InnerWeaver.ReadModule () [0x00052] in <f6f9069078364b4db60945017a527c4a>:0 
  at InnerWeaver.Execute () [0x00019] in <f6f9069078364b4db60945017a527c4a>:0

**Comment by valdetero** [comment]
I have been seeing this issue for a few weeks. This was happening with Mono 5.0.0.42.

**Comment by yevgeniy-seleznev** [comment]
Issue no longer persists after also upgrading Fody to 2.0.7.

**Comment by valdetero** [comment]
That error is fixed but I get new errors when upgrading. "The weaver assembly ' ... ' references an out of date version of mono.cecil.dll. At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.". I can't add FodyCecil since it isn't compatible with a PCL. Also, the weavers I am using haven't been updated to 0.10.

**Comment by yevgeniy-seleznev** [comment]
Another workaround I've read is to downgrade your runtime back to mono 4.8.

**Comment by SimonCropp** [comment]
@valdetero you should not need to use the FodyCecil nuget to use fody. it is only used by people building weavers, and all weavers run in the 4.5.2 runtime, hence no PCL is required

**Comment by SimonCropp** [comment]
@yevgeniy-seleznev so u r still experiencing out of mem when using all the newest nugets?

**Comment by yevgeniy-seleznev** [comment]
No, I no longer see the out of mem exception after upgrading to Fody 2.0.7. Running stable mono 5.0. Also, not using FodyCecil nuget.

**Comment by xplatsolutions** [comment]
@SimonCropp 
I have issues after updating Xamarin Studio. I use Fody, Anotar.Splat.Fody, ReactiveUI.Fody. I have updated Fody and ReactiveUI.Fody but unable to update Anotar.Splat.Fody due to Splat constraints and ReactiveUI. Any ideas regarding the below message?

> Error: Fody: The weaver assembly 'Anotar.Splat.Fody, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0. 

@yevgeniy-seleznev  As an alternative do you know how to downgrade Xamarin iOS?

**Comment by valdetero** [comment]
@xplatsolutions it's not xamarin.ios, it's the mono framework. Either go to the mono site and download mono 4.8 stand alone and install it or you can open Xamarin Studio (VS for Mac) -> Preferences -> Build / Net Runtimes and if you have both 5.0 and 4.8 listed, then set 4.8 to default. It should build after a clean (and maybe a restart).

**Comment by xplatsolutions** [comment]
Cool, I didn't know the trick with choosing the runtime there. I have downgraded to make it work again. Will have in mind if I want to upgrade the other components, for now, no real reason to do so.

**Comment by valdetero** [comment]
@SimonCropp if I don't need FodyCecil, then why is it giving a build error that I do?

**Comment by SimonCropp** [comment]
@valdetero can u share the build error and also share a solution that repros the problem

**Comment by SimonCropp** [comment]
@valdetero 

>  "The weaver assembly ' ... ' references an out of date version of mono.cecil.dll. At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.".

this means one of the weavers you are using is out of date with fody 2.0. you need to ensure they are all up to date, and if u still get the error raise an issue in the specific weaver that causes the problem

**Comment by SimonCropp** [comment]
@xplatsolutions  unfortunatly if u cant update your reference tree you cant update fody and anotar. i suggest you contact the Splat team and ask them about updating reactive UI

**Comment by SimonCropp** [comment]
@yevgeniy-seleznev thanks for the confirmation. i will close this one
